ERFs:
- DirectEff
- ERFsurfswcs
- SWDirectEff
- atmabs
- ERFsurf
- ERFsurflw
- ERFsurfcs
- LWCloudEff
- atmabsSW
- SWCloudEff
- ERFt
- ERFtsw
- ERFtlw
- LWDirectEff
- CloudEff
derived_vars:
- conch2oaer
- concso4
- concdust
- cdncvi
- concoa
vars:
- rsdscs
- rsds
- emidust
- od870aer
- sfcWind
- clivi
- pr
- od440aer
- prc
- od550aer
- clwvi
- evspsbl
- clt
- depdust
- abs550aer
