ERFs:
- DirectEff
- ERFsurfswcs
- ERFsurflw
- atmabs
- ERFsurfcs
- atmabsSW
- ERFtlw
- ERFtsw
- LWCloudEff
- CloudEff
- ERFtcsaf
- ERFsurf
- SWCloudEff
- SWDirectEff
- ERFt
- LWDirectEff
derived_vars:
- cdncvi
- concoa
- concdust
- concso4
- conch2oaer
vars:
- rsds
- emidust
- evspsbl
- od870aer
- rsdscs
- pr
- sfcWind
- od440aer
- od550aer
- clivi
- depdust
- prc
- abs550aer
- clt
- clwvi
