ERFs:
- DirectEff
- ERFtlw
- ERFsurf
- atmabsSW
- CloudEff
- ERFsurfswcs
- LWDirectEff
- ERFsurflw
- SWCloudEff
- ERFtsw
- ERFsurfcs
- atmabs
- SWDirectEff
- LWCloudEff
- ERFt
derived_vars:
- conch2oaer
- concdust
- concso4
- cdncvi
- concoa
vars:
- od870aer
- od550aer
- evspsbl
- abs550aer
- clivi
- emidust
- depdust
- clt
- od440aer
- sfcWind
- clwvi
- prc
- pr
- rsds
- rsdscs
